In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel("employee_salary.xlsx")

In [4]:
df = pd.read_excel("employee_salary.xlsx")
df

,Employee_ID,Age,Gender,Education_Level,Experience_Years,Job_Role,Department,Location,Work_Mode,Performance_Rating,Overtime,Salary
0,EMP0001,35,Male,Bachelor,7,Content Writer,Marketing,Pune,Hybrid,3,No,736050
1,EMP0002,49,Male,Bachelor,14,Content Writer,Marketing,Bangalore,Hybrid,5,Yes,1398725
2,EMP0003,39,Male,Bachelor,15,HR Executive,HR,Mumbai,Office,3,No,1277748
3,EMP0004,47,Female,Master,6,Network Engineer,IT,Chennai,Office,3,Yes,854144
4,EMP0005,32,Male,Master,11,AI Engineer,AI,Mumbai,Office,3,No,1159491
...,...,...,...,...,...,...,...,...,...,...,...,...
495,EMP0496,40,Female,Bachelor,17,Cloud Engineer,IT,Hyderabad,Hybrid,5,Yes,1659693
496,EMP0497,29,Female,Bachelor,8,Recruiter,HR,Delhi,Hybrid,3,No,786688
497,EMP0498,39,Female,Master,2,Network Engineer,IT,Bangalore,Remote,3,No,526665
498,EMP0499,33,Male,Bachelor,8,DevOps Engineer,IT,Chennai,Office,5,No,936549
499,EMP0500,26,Male,Bachelor,5,DevOps Engineer,IT,Bangalore,Hybrid,5,No,768264

In [8]:
df.head()

,Employee_ID,Age,Gender,Education_Level,Experience_Years,Job_Role,Department,Location,Work_Mode,Performance_Rating,Overtime,Salary
0,EMP0001,35,Male,Bachelor,7,Content Writer,Marketing,Pune,Hybrid,3,No,736050
1,EMP0002,49,Male,Bachelor,14,Content Writer,Marketing,Bangalore,Hybrid,5,Yes,1398725
2,EMP0003,39,Male,Bachelor,15,HR Executive,HR,Mumbai,Office,3,No,1277748
3,EMP0004,47,Female,Master,6,Network Engineer,IT,Chennai,Office,3,Yes,854144
4,EMP0005,32,Male,Master,11,AI Engineer,AI,Mumbai,Office,3,No,1159491

In [9]:
df.tail(10)

,Employee_ID,Age,Gender,Education_Level,Experience_Years,Job_Role,Department,Location,Work_Mode,Performance_Rating,Overtime,Salary
490,EMP0491,43,Male,Bachelor,13,AI Engineer,AI,Chennai,Hybrid,4,Yes,1230496
491,EMP0492,40,Female,Master,9,Data Analyst,Analytics,Pune,Office,4,Yes,1003428
492,EMP0493,22,Male,Master,1,Project Manager,Management,Bangalore,Hybrid,5,No,934331
493,EMP0494,23,Female,Bachelor,2,Business Analyst,Business,Chennai,Remote,3,No,373930
494,EMP0495,49,Female,Bachelor,3,Data Scientist,Analytics,Pune,Hybrid,5,No,647017
495,EMP0496,40,Female,Bachelor,17,Cloud Engineer,IT,Hyderabad,Hybrid,5,Yes,1659693
496,EMP0497,29,Female,Bachelor,8,Recruiter,HR,Delhi,Hybrid,3,No,786688
497,EMP0498,39,Female,Master,2,Network Engineer,IT,Bangalore,Remote,3,No,526665
498,EMP0499,33,Male,Bachelor,8,DevOps Engineer,IT,Chennai,Office,5,No,936549
499,EMP0500,26,Male,Bachelor,5,DevOps Engineer,IT,Bangalore,Hybrid,5,No,768264

In [10]:
df.shape
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Number of Rows: 500
Number of Columns: 12

In [11]:
df.columns
print(df.columns)

Index(['Employee_ID', 'Age', 'Gender', 'Education_Level', 'Experience_Years',
       'Job_Role', 'Department', 'Location', 'Work_Mode', 'Performance_Rating',
       'Overtime', 'Salary'],
      dtype='str')

In [12]:
df.index

RangeIndex(start=0, stop=500, step=1)

In [14]:
df[['Employee_ID', 'Age', 'Salary']]

    Employee_ID  Age   Salary
0       EMP0001   35   736050
1       EMP0002   49  1398725
2       EMP0003   39  1277748
3       EMP0004   47   854144
4       EMP0005   32  1159491
..          ...  ...      ...
495     EMP0496   40  1659693
496     EMP0497   29   786688
497     EMP0498   39   526665
498     EMP0499   33   936549
499     EMP0500   26   768264

[500 rows x 3 columns]

In [16]:
df['Salary']

0       736050
1      1398725
2      1277748
3       854144
4      1159491
        ...
495    1659693
496     786688
497     526665
498     936549
499     768264
Name: Salary, Length: 500, dtype: int64

In [17]:
df.iloc[0]
df.iloc[0:5]

,Employee_ID,Age,Gender,Education_Level,Experience_Years,Job_Role,Department,Location,Work_Mode,Performance_Rating,Overtime,Salary
0,EMP0001,35,Male,Bachelor,7,Content Writer,Marketing,Pune,Hybrid,3,No,736050
1,EMP0002,49,Male,Bachelor,14,Content Writer,Marketing,Bangalore,Hybrid,5,Yes,1398725
2,EMP0003,39,Male,Bachelor,15,HR Executive,HR,Mumbai,Office,3,No,1277748
3,EMP0004,47,Female,Master,6,Network Engineer,IT,Chennai,Office,3,Yes,854144
4,EMP0005,32,Male,Master,11,AI Engineer,AI,Mumbai,Office,3,No,1159491

In [19]:
len(df)

500

In [20]:
len(df.columns)

12